// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using biz.conevento.Entities;

namespace dal.conevento.DBContext
{
    public partial class Db_ConeventoContext : DbContext
    {
        public Db_ConeventoContext()
        {
        }

        public Db_ConeventoContext(DbContextOptions<Db_ConeventoContext> options)
            : base(options)
        {
        }

        public virtual DbSet<CatCategoriaProducto> CatCategoriaProductos { get; set; }
        public virtual DbSet<CatProductosServicio> CatProductosServicios { get; set; }
        public virtual DbSet<Evento> Eventos { get; set; }
        public virtual DbSet<User> Users { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<CatCategoriaProducto>(entity =>
            {
                entity.ToTable("Cat_categoria_productos");

                entity.Property(e => e.Id).HasColumnName("id");

                entity.Property(e => e.Categoria)
                    .HasColumnName("categoria")
                    .HasMaxLength(50);
            });

            modelBuilder.Entity<CatProductosServicio>(entity =>
            {
                entity.ToTable("cat_productos_servicios");

                entity.Property(e => e.Id)
                    .HasColumnName("id")
                    .ValueGeneratedNever();

                entity.Property(e => e.DescripcionCorta)
                    .HasColumnName("descripcion_corta")
                    .HasMaxLength(300);

                entity.Property(e => e.DescripcionLarga)
                    .HasColumnName("descripcion_larga")
                    .HasMaxLength(300);

                entity.Property(e => e.DiasBloqueoAntes).HasColumnName("dias_bloqueo_antes");

                entity.Property(e => e.DiasBloqueoDespues).HasColumnName("dias_bloqueo_despues");

                entity.Property(e => e.IdCategoriaProducto).HasColumnName("id_categoria_producto");

                entity.Property(e => e.PrecioPorUnidad)
                    .HasColumnName("precio_por_unidad")
                    .HasMaxLength(50);

                entity.Property(e => e.Producto)
                    .HasColumnName("producto")
                    .HasMaxLength(50);

                entity.Property(e => e.Unidad)
                    .HasColumnName("unidad")
                    .HasMaxLength(50);

                entity.HasOne(d => d.IdCategoriaProductoNavigation)
                    .WithMany(p => p.CatProductosServicios)
                    .HasForeignKey(d => d.IdCategoriaProducto)
                    .HasConstraintName("FK_cat_productos_servicios_Cat_categoria_productos");
            });

            modelBuilder.Entity<Evento>(entity =>
            {
                entity.Property(e => e.Id).HasColumnName("id");

                entity.Property(e => e.Apellidos)
                    .HasColumnName("apellidos")
                    .HasMaxLength(150);

                entity.Property(e => e.Colonia)
                    .HasColumnName("colonia")
                    .HasMaxLength(10)
                    .IsFixedLength();

                entity.Property(e => e.Correo)
                    .HasColumnName("correo")
                    .HasMaxLength(50);

                entity.Property(e => e.Cp)
                    .HasColumnName("cp")
                    .HasMaxLength(50);

                entity.Property(e => e.DetallesEvento)
                    .HasColumnName("detalles_evento")
                    .HasMaxLength(500);

                entity.Property(e => e.Direccion)
                    .HasColumnName("direccion")
                    .HasMaxLength(500);

                entity.Property(e => e.Estado).HasColumnName("estado");

                entity.Property(e => e.FechaCreacion)
                    .HasColumnName("fecha_creacion")
                    .HasColumnType("datetime");

                entity.Property(e => e.FechaPago)
                    .HasColumnName("fecha_pago")
                    .HasColumnType("datetime");

                entity.Property(e => e.Fin)
                    .HasColumnName("fin")
                    .HasColumnType("datetime");

                entity.Property(e => e.FormaPago).HasColumnName("forma_pago");

                entity.Property(e => e.GenteEsperada).HasColumnName("gente_esperada");

                entity.Property(e => e.IdUsuario).HasColumnName("id_usuario");

                entity.Property(e => e.Inicio)
                    .HasColumnName("inicio")
                    .HasColumnType("datetime");

                entity.Property(e => e.Municipio).HasColumnName("municipio");

                entity.Property(e => e.NombreEvento)
                    .HasColumnName("nombre_evento")
                    .HasMaxLength(50);

                entity.Property(e => e.Nombres)
                    .HasColumnName("nombres")
                    .HasMaxLength(150);

                entity.Property(e => e.NumExt)
                    .HasColumnName("num_ext")
                    .HasMaxLength(50);

                entity.Property(e => e.NumInt)
                    .HasColumnName("num_int")
                    .HasMaxLength(50);

                entity.Property(e => e.ReferenciaPago)
                    .HasColumnName("referencia_pago")
                    .HasMaxLength(500);

                entity.Property(e => e.Telefono)
                    .HasColumnName("telefono")
                    .HasMaxLength(50);

                entity.HasOne(d => d.IdUsuarioNavigation)
                    .WithMany(p => p.Eventos)
                    .HasForeignKey(d => d.IdUsuario)
                    .HasConstraintName("FK_Eventos_users");
            });

            modelBuilder.Entity<User>(entity =>
            {
                entity.ToTable("users");

                entity.Property(e => e.Id).HasColumnName("id");

                entity.Property(e => e.Apellidos)
                    .HasColumnName("apellidos")
                    .HasMaxLength(100);

                entity.Property(e => e.Correo)
                    .IsRequired()
                    .HasColumnName("correo")
                    .HasMaxLength(200);

                entity.Property(e => e.Estado).HasColumnName("estado");

                entity.Property(e => e.Estatus).HasColumnName("estatus");

                entity.Property(e => e.FechaCreacion)
                    .HasColumnName("fecha_creacion")
                    .HasColumnType("datetime");

                entity.Property(e => e.FechaEdicion)
                    .HasColumnName("fecha_edicion")
                    .HasColumnType("datetime");

                entity.Property(e => e.Municipio).HasColumnName("municipio");

                entity.Property(e => e.Nombres)
                    .HasColumnName("nombres")
                    .HasMaxLength(100);

                entity.Property(e => e.Pass)
                    .IsRequired()
                    .HasColumnName("pass")
                    .HasMaxLength(50);

                entity.Property(e => e.Telefono)
                    .HasColumnName("telefono")
                    .HasMaxLength(200);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}