// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace biz.conevento.Entities
{
    public partial class CatCategoriaProducto
    {
        public CatCategoriaProducto()
        {
            CatProductosServicios = new HashSet<CatProductosServicio>();
        }

        public int Id { get; set; }
        public string Categoria { get; set; }

        public virtual ICollection<CatProductosServicio> CatProductosServicios { get; set; }
    }
}