// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace biz.conevento.Entities
{
    public partial class CatProductosServicio
    {
        public int Id { get; set; }
        public string Producto { get; set; }
        public string DescripcionCorta { get; set; }
        public string DescripcionLarga { get; set; }
        public int? IdCategoriaProducto { get; set; }
        public string Unidad { get; set; }
        public string PrecioPorUnidad { get; set; }
        public int? DiasBloqueoAntes { get; set; }
        public int? DiasBloqueoDespues { get; set; }

        public virtual CatCategoriaProducto IdCategoriaProductoNavigation { get; set; }
    }
}