// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.conevento.Entities
{
    public partial class Cupone
    {
        public Cupone()
        {
            Eventos = new HashSet<Evento>();
        }

        public int Id { get; set; }
        public string Nombre { get; set; }
        public DateTime FechaInicial { get; set; }
        public DateTime FechaFinal { get; set; }
        public int NumeroCupones { get; set; }
        public decimal MontoPesos { get; set; }
        public int MontoPorcentaje { get; set; }
        public bool Estatus { get; set; }
        public int Type { get; set; }

        public virtual ICollection<Evento> Eventos { get; set; }
    }
}