// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.conevento.Entities
{
    public partial class Evento
    {
        public int Id { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public string NombreEvento { get; set; }
        public DateTime? Inicio { get; set; }
        public DateTime? Fin { get; set; }
        public int? FormaPago { get; set; }
        public string Telefono { get; set; }
        public string Correo { get; set; }
        public int? IdUsuario { get; set; }
        public int Estado { get; set; }
        public int Municipio { get; set; }
        public int GenteEsperada { get; set; }
        public string Direccion { get; set; }
        public string NumInt { get; set; }
        public string NumExt { get; set; }
        public string Cp { get; set; }
        public string Colonia { get; set; }
        public DateTime? FechaCreacion { get; set; }
        public string DetallesEvento { get; set; }
        public DateTime? FechaPago { get; set; }
        public string ReferenciaPago { get; set; }

        public virtual User IdUsuarioNavigation { get; set; }
    }
}