// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace biz.conevento.Entities
{
    public partial class VariablesSistema
    {
        public int Id { get; set; }
        public string Variable { get; set; }
        public string ValorVariable { get; set; }
        public string Descripcion { get; set; }
    }
}